### ISSUE TITLE
What do you hope to gain from this AMA thread? 

### ISSUE THREAD

**Issue by CarlMungazi** [brenopolanski/ama#1]

**Comment by brenopolanski** [comment]
Hey @CarlMungazi 

I want to spend a little of my experience. I think we can learn together with the AMA thread ;)

**Comment by CarlMungazi** [comment]
Great @brenopolanski!

What is the biggest code-related mistake you have made?

**Comment by brenopolanski** [comment]
Hey @CarlMungazi 

Was attempting to use technologies that I have no experience, and it made me lose a little time on the project.
