### ISSUE TITLE
Screenshot of your phone homescreen

### ISSUE THREAD

**Issue by AchoArnold** [brenopolanski/ama#3]

**Comment by brenopolanski** [comment]
@AchoArnold What?

**Comment by AchoArnold** [comment]
@brenopolanski e.g https://github.com/ireade/ama/issues/11#event-1025558110

**Comment by brenopolanski** [comment]
Okay... But what are you thinking of doing with these screenshots @AchoArnold?

**Comment by AchoArnold** [comment]
It says a lot about a person ... [proof](http://www.dailytelegraph.com.au/news/nsw/your-smartphone-homescreen-can-reveal-a-lot-about-you-clinical-psychologist-says/news-story/16c0b6d1f5a88ceafa9c77dac71c2bae)

Also I'm trying to continue https://github.com/sindresorhus/ama/issues/64

**Comment by brenopolanski** [comment]
For now i'm using WP10 :smile:

![wp_ss_20170427_0001](https://cloud.githubusercontent.com/assets/1894191/25498506/9ae699b8-2b5e-11e7-9799-34cb3e7d8d76.png)

**Comment by AchoArnold** [comment]
You see just using a windows phone says a lot (eg _"I want to be different"_)
